# Generated by Django 5.2.5 on 2025-09-17 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('home_jersey', 'Home jersey'), ('away_jersey', 'Away jersey'), ('third_jersey', 'Third jersey'), ('goalkeeper_jersey', 'Goalkeeper jersey'), ('thrift_jersey', 'Thrift jersey'), ('special_jersey', 'Special jersey')], default='home_jersey', max_length=20),
        ),
    ]
